Milestone 2
rociac/bookstore pull request #2
Opened 2020-02-19 18:59 UTC by rociac

This branch contains all the main components, the initial Redux store, actions and reducers.

2020-02-19 20:49 UTC, shloch requested changes
## great job @rociac , @Juakata 

AWESOME JOB
### PLEASE RELOCATE 2 FILES MENTIONED BELOW AND FILE FOR LAST REVIEW, thats all you have to do guys.......... :)

2020-02-19 20:49 UTC, shloch commented on src/components/BooksForm.js
> +
this component should be placed in  `src/containers` directory

2020-02-19 20:49 UTC, shloch commented on src/components/BooksList.js
> +  ));
this component should be placed in  `src/containers` directory

2020-02-19 20:55 UTC, rociac commented
Made the requested changes :)

2020-02-20 02:01 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-02-20 14:55 UTC, merged