Milestone 3
rociac/bookstore pull request #3
Opened 2020-02-20 19:32 UTC by Juakata

This branch contains createBook and removeBook functionalities.

2020-02-21 09:25 UTC, bolah2009 requested changes
# Hi Team 🙋🏽‍♂

Nice job with the `remove` and `add` implementation.  👏🏾

There is one required changes need to be made, see comment below.

#### :recycle:  Make these changes and submit another code review request. 👍🏾

#### Feel free to reach me on slack if you having issues implementing these features. :relaxed: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-02-21 09:25 UTC, bolah2009 commented on src/components/Book.js
> +  const { book, onClick } = props;
[Optional]

We could destructure the `book` and `onClick` directly from the parameter.

```diff
- const Book = props => {
+ const ({ book, onClick }) = props => {
-  const { book, onClick } = props;
```

2020-02-21 09:25 UTC, bolah2009 commented on src/containers/BooksForm.js
> +      </form>
[Optional]

If the `onSubmit` event is used on the `form` element with `this.handleSubmit` as the handler, we can add `required` attribute to the `input` field to prevent creating a book without a title, the `button` would be of type `submit` and the `onClick` removed, this helps to add native HTML form validation to the `BoookForm` component.

| Current | Preferred |
|:-----:|:----:|
|![empty-book-store](https://user-images.githubusercontent.com/36057474/75017194-d7267d80-548c-11ea-941a-f5a0a8d917a1.gif) | ![validated-book-store](https://user-images.githubusercontent.com/36057474/75018321-f7efd280-548e-11ea-9aa7-708b0291c2f6.gif) |

2020-02-21 09:25 UTC, bolah2009 commented on src/containers/BooksForm.js
> +  }
The `handleSubmit` should reset the component's state after saving the new book.
Let's reset the book title and category, see screenshot

| Current | Preferred |
|:-----:|:----:|
| ![no-reset](https://user-images.githubusercontent.com/36057474/75018252-d393f600-548e-11ea-8b13-53674daf9f13.gif) | ![fix-reset](https://user-images.githubusercontent.com/36057474/75018983-608b7f00-5490-11ea-9b75-8df5ed6df8e5.gif) |


> The component should implement `handleSubmit` which will save the new book in the Redux store and resets the component’s state.
Screenshot from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896828/)
![image](https://user-images.githubusercontent.com/36057474/75019060-82850180-5490-11ea-89aa-af591644e8af.png)

2020-02-21 19:12 UTC, azdrenymeri commented
### Hello @Juakata and @rociac 
- [x] every time you add a book the form is reset. :+1: 
#### There are no further requirements, you can merge :heavy_check_mark:

2020-02-22 07:41 UTC, bolah2009 commented on src/containers/BooksForm.js
>          <button type="submit" onSubmit={this.handleSubmit}>Submit</button>
We can delete the additional `onSubmit` in the `button` element.
```suggestion
        <button type="submit" >Submit</button>
```

2020-02-24 14:42 UTC, merged